
server:
  port: 9191

spring:
  datasource:
    password: password
    url: jdbc:sqlserver://172.172.172.172\INFORLN:1434;databaseName=erplndb
    username: sa
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
